### ISSUE TITLE
I want to know how to train the model

### ISSUE THREAD

**Issue by LiuDong777** [vsubhashini/noc#6]
hi 
I want to reproduce your experiment，in the code to generate .h5 file 
  POOLFEAT_FILE_PATTERN = 'data/coco2014/coco2014_{0}_vgg_fc7.txt'
 SENTS_FILE_PATTERN = 'data/coco2014/sents/coco_sentences_{0}_tokens.txt'
 LABEL_FILE_PATTERN = 'data/coco2014/sents/labels_glove72k_{0}.txt' #train2014
 # IMAGEID_FILE_PATTERN = 'data/coco2014/coco_rm8objs_image_list_{0}.txt'
 IMAGEID_FILE_PATTERN = 'data/coco2014/cvpr17_rm8newobjs/coco_rm8newobjs_image_list_{0}.txt'
 i want to know how can i get these handled documents like coco2014_{0}_vgg_fc7.txt?
  I am a beginner，I am so sorry to take up your time.  Can you tell me how to reproduce  your experiment?
 thank you!

**Comment by vsubhashini** [comment]
Sorry about that, I should probably include more comprehensive instructions.

I have provided the links to download the raw training data:
https://github.com/LisaAnne/DCC
This imageid file pattern is just a list of image IDs for the train, test,
and validation splits.

The file names in the scripts (within data_utils) should point to the
train, validation, and test splits of the data. I have also included the
script that extracts labels from the captions.

vgg_fc7: should contain the image features (from VGG net). Can be extracted
using:
https://github.com/vsubhashini/noc/blob/recurrent/examples/noc/extract_vgg_features.py
-- Just create a file with a list of images and this script will help you
extract VGG features.

Hope this helps.

On Jan 9, 2018 2:52 AM, "dong798" <notifications@github.com> wrote:

hi
I want to reproduce your experiment，in the code to generate .h5 file
POOLFEAT_FILE_PATTERN = 'data/coco2014/coco2014_{0}
*vgg_fc7.txt' SENTS_FILE_PATTERN = 'data/coco2014/sents/coco_sentences*{0}
*tokens.txt' LABEL_FILE_PATTERN = 'data/coco2014/sents/labels_glove72k*{0}.txt'
#train2014
IMAGEID_FILE_PATTERN = 'data/coco2014/coco_rm8objs_image_list_{0}.txt'

IMAGEID_FILE_PATTERN = 'data/coco2014/cvpr17_rm8newobjs/coco_rm8newobjs_
image_list_{0}.txt'
i want to know how can i get these handled documents like
coco2014_{0}_vgg_fc7.txt?
I am a beginner，I am so sorry to take up your time. Can you tell me how to
reproduce your experiment?
thank you!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vsubhashini/noc/issues/6>, or mute the thread

**Comment by LiuDong777** [comment]
What your means is that
POOLFEAT_FILE_PATTERN = 'data / coco2014 / coco2014_ {0} _vgg_fc7.txt'
is the feature of the training data(train2014), and IMAGEID_FILE_PATTERN is the list of data
right?
but how about the LABEL_FILE_PATTERN?

**Comment by vsubhashini** [comment]
Yes. The coco ID lists are actually all here: https://github.com/
vsubhashini/noc/blob/recurrent/examples/noc/data_utils/image_list/
<https://github.com/vsubhashini/noc/blob/recurrent/examples/noc/data_utils/image_list/coco2014_cocoid.train.txt>

The label list is the list of labels corresponding to the images. For
Imagenet it would just be a single label for each image, for COCO it's
extracted from the captions. But you make a good point looks like I have
not included the code that extracts the labels or the labels list.
Will add them. Thanks!

**Comment by Sally-fyk** [comment]
Where can I find the code that extracts the labels or the labels list ?
